name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock
          pip install -e .[dev]
      - name: Lint
        run: ruff check .
      - name: Run tests
        run: pytest
      - name: Quick analysis smoke test
        env:
          PYTHON: python
        run: make quick SEED=123
      - name: Upload quick artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quick-run-${{ matrix.python-version }}
          path: |
            results/quick_run/**
